### ISSUE TITLE
LIST on Direct Message crash

### ISSUE THREAD

**Issue by Scrxtchy** [creesch/discordIRCd#10]
The deamon will crash if a user inputs a LIST command for any reason when connecting to the `DMServer`

```
data: LIST                                                                                        │··························
                                                                                                  │··························
/mnt/mpathag/scratch/node/discordIRCd/server.js:693                                               │··························
    const channels = discordClient.guilds.get(discordID).channels.array();                        │··························
                                                        ^                                         │··························
                                                                                                  │··························
TypeError: Cannot read property 'channels' of undefined                                           │··························
    at listCommand (/mnt/mpathag/scratch/node/discordIRCd/server.js:693:57)                       │··························
    at /mnt/mpathag/scratch/node/discordIRCd/server.js:933:25                                     │··························
    at Array.forEach (native)                                                                     │··························
    at Socket.<anonymous> (/mnt/mpathag/scratch/node/discordIRCd/server.js:779:19)                │··························
    at emitOne (events.js:96:13)                                                                  │··························
    at Socket.emit (events.js:189:7)                                                              │··························
    at readableAddChunk (_stream_readable.js:176:18)                                              │··························
    at Socket.Readable.push (_stream_readable.js:134:10)                                          │··························
    at TCP.onread (net.js:551:20)     
```

**Comment by creesch** [comment]
Right, that is because that server will never have channels. I'll build in a check to prevent this from happening.
