### ISSUE TITLE
discordIRCd crashes when a channel it's on is renamed

### ISSUE THREAD

**Issue by rctgamer3** [creesch/discordIRCd#29]
Title.

**Comment by Scrxtchy** [comment]
Could be handled with a SAJOIN I assume

**Comment by creesch** [comment]
Shouldn't do that, in fact doesn't for me. Got any logging for me?

**Comment by rctgamer3** [comment]
```
debug Sending heartbeat
debug Heartbeat acknowledged
channel updated
channel name changed from #shakespeare to #the-ballpit
/home/rctgamer3/discordIRCd/server.js:625
            if (socket.discordid === discordServerId && ircDetails[discordServerId].channels[oldChannel.name].joined.indexOf(socket.ircid) > -1) {
                                                                                                             ^

TypeError: Cannot read property 'joined' of undefined
    at /home/rctgamer3/discordIRCd/server.js:625:110
    at Array.forEach (native)
    at Client.<anonymous> (/home/rctgamer3/discordIRCd/server.js:624:20)
    at emitTwo (events.js:106:13)
    at Client.emit (events.js:194:7)
    at ChannelUpdateAction.handle (/home/rctgamer3/discordIRCd/node_modules/discord.js/src/client/actions/ChannelUpdate.js:13:14)
    at ChannelUpdateHandler.handle (/home/rctgamer3/discordIRCd/node_modules/discord.js/src/client/websocket/packets/handlers/ChannelUpdate.js:7:34)
    at WebSocketPacketManager.handle (/home/rctgamer3/discordIRCd/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/rctgamer3/discordIRCd/node_modules/discord.js/src/client/websocket/WebSocketManager.js:273:31)
    at WebSocket.onMessage (/home/rctgamer3/discordIRCd/node_modules/ws/lib/WebSocket.js:442:14)
```

**Comment by creesch** [comment]
Hrm.... That would be this line. 

https://github.com/creesch/discordIRCd/blob/master/server.js#L625

It seems that in this instance both the channel name changed and the topic a situation I didn't think about but can obviously occur.
