### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Volkor3-16** [creesch/discordIRCd#55]
Happens randomly, no idea what's causing it. If I'm able to reproduce it properly I'll update here later

```
/home/volkor/git/discordIRCd/server.js:599
    const discordServerId = oldChannel.guild.id;
                                             ^

TypeError: Cannot read property 'id' of undefined
    at Client.<anonymous> (/home/volkor/git/discordIRCd/server.js:599:46)
    at Client.emit (events.js:198:13)
    at ChannelUpdateAction.handle (/home/volkor/git/discordIRCd/node_modules/discord.js/src/client/actions/ChannelUpdate.js:13:14)
    at ChannelUpdateHandler.handle (/home/volkor/git/discordIRCd/node_modules/discord.js/src/client/websocket/packets/handlers/ChannelUpdate.js:7:34)
    at WebSocketPacketManager.handle (/home/volkor/git/discordIRCd/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/volkor/git/discordIRCd/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/volkor/git/discordIRCd/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/volkor/git/discordIRCd/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver._receiver.onmessage (/home/volkor/git/discordIRCd/node_modules/ws/lib/websocket.js:137:47)
```

**Comment by rctgamer3** [comment]
Does this still occur? Can you check with the latest version?

**Comment by Volkor3-16** [comment]
No, sorry, I migrated from IRC to matrix, all my configs for this are gone :(
