### ISSUE TITLE
NPM install errors: dependency issues?

### ISSUE THREAD

**Issue by tamberoo** [creesch/discordIRCd#56]
Hi all,

It seems running `npm install` on my machine for discordIRCd does not work properly.
I don't totally know what I'm doing, but judging from what I can gather from my terminal's output after trying `npm install`, it looks like discordIRCd might require all sorts of specific versions of .js material, which is why I titled this "[...] dependency issues?".

Running `git clone` to clone the git to my home directory works fine, no problems there.

Afterwards,
`tamberoo@studio1:~/discordIRCd$ npm install`
`loadDep:erlpack → resolve ▐ ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟`
`loadDep:erlpack → get     ▐ ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟`
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated snekfetch@3.6.4: use node-fetch instead`
`loadDep:uuid → headers    ▌ ╢████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟`
`loadDep:punycode → 200    ▀ ╢█████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟`
` `
` > bufferutil@3.0.5 install /home/tamberoo/discordIRCd/node_modules/bufferutil`
` > prebuild-install || node-gyp rebuild`
` `
`/usr/bin/env: ‘node’: No such file or directory`
`/bin/sh: 1: node: not found`
`gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp`
`gyp ERR! configure error `
`gyp ERR! stack Error: `gyp` failed with exit code: 1`
`gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)`
`gyp ERR! stack     at emitTwo (events.js:87:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:172:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)`
`gyp ERR! System Linux 4.4.0-142-generic`
`gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"`
`gyp ERR! cwd /home/tamberoo/discordIRCd/node_modules/bufferutil`
`gyp ERR! node -v v4.2.6`
`gyp ERR! node-gyp -v v3.0.3`
`gyp ERR! not ok `
`discord-ircd@0.5.0 /home/tamberoo/discordIRCd`
`├── UNMET PEER DEPENDENCY @discordjs/opus@^0.1.0`
`├── UNMET PEER DEPENDENCY @discordjs/uws@^10.149.0`
`├── UNMET DEPENDENCY bufferutil@^3.0.0`
`├─┬ discord.js@11.6.4 `
`│ ├── long@4.0.0 `
`│ ├── prism-media@0.0.4 `
`│ ├── snekfetch@3.6.4 `
`│ ├── tweetnacl@1.0.3 `
`│ └─┬ ws@6.2.1 `
`│   └── async-limiter@1.0.1 `
`├─┬ UNMET PEER DEPENDENCY erlpack@0.1.3 (git://github.com/hammerandchise/erlpack.git#c514d36ec81a7a61ef90b75df261025ab046574d)`
`│ ├─┬ bindings@1.5.0 `
`│ │ └── file-uri-to-path@1.0.0 `
`│ └── nan@2.14.0 `
`├── UNMET PEER DEPENDENCY libsodium-wrappers@^0.7.3`
`├── UNMET PEER DEPENDENCY node-opus@^0.2.7`
`├── UNMET PEER DEPENDENCY opusscript@^0.0.6`
`├─┬ request@2.88.2 `
`│ ├── aws-sign2@0.7.0 `
`│ ├── aws4@1.9.1 `
`│ ├── caseless@0.12.0 `
`│ ├─┬ combined-stream@1.0.8 `
`│ │ └── delayed-stream@1.0.0 `
`│ ├── extend@3.0.2 `
`│ ├── forever-agent@0.6.1 `
`│ ├─┬ form-data@2.3.3 `
`│ │ └── asynckit@0.4.0 `
`│ ├─┬ har-validator@5.1.3 `
`│ │ ├─┬ ajv@6.12.0 `
`│ │ │ ├── fast-deep-equal@3.1.1 `
`│ │ │ ├── fast-json-stable-stringify@2.1.0 `
`│ │ │ ├── json-schema-traverse@0.4.1 `
`│ │ │ └── uri-js@4.2.2 `
`│ │ └── har-schema@2.0.0 `
`│ ├─┬ http-signature@1.2.0 `
`│ │ ├── assert-plus@1.0.0 `
`│ │ ├─┬ jsprim@1.4.1 `
`│ │ │ ├── extsprintf@1.3.0 `
`│ │ │ ├── json-schema@0.2.3 `
`│ │ │ └─┬ verror@1.10.0 `
`│ │ │   └── core-util-is@1.0.2 `
`│ │ └─┬ sshpk@1.16.1 `
`│ │   ├── asn1@0.2.4 `
`│ │   ├─┬ bcrypt-pbkdf@1.0.2 `
`│ │   │ └── tweetnacl@0.14.5 `
`│ │   ├── dashdash@1.14.1 `
`│ │   ├── ecc-jsbn@0.1.2 `
`│ │   ├── getpass@0.1.7 `
`│ │   ├── jsbn@0.1.1 `
`│ │   ├── safer-buffer@2.1.2 `
`│ │   └── tweetnacl@0.14.5 `
`│ ├── is-typedarray@1.0.0 `
`│ ├── isstream@0.1.2 `
`│ ├── json-stringify-safe@5.0.1 `
`│ ├─┬ mime-types@2.1.26 `
`│ │ └── mime-db@1.43.0 `
`│ ├── oauth-sign@0.9.0 `
`│ ├── performance-now@2.1.0 `
`│ ├── qs@6.5.2 `
`│ ├── safe-buffer@5.1.2 `
`│ ├─┬ tough-cookie@2.5.0 `
`│ │ ├── psl@1.8.0 `
`│ │ └── punycode@2.1.1 `
`│ ├── tunnel-agent@0.6.0 `
`│ └── uuid@3.4.0 `
`└── UNMET PEER DEPENDENCY sodium@^2.0.3`

`npm WARN discord.js@11.6.4 requires a peer of @discordjs/uws@^10.149.0 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of bufferutil@^4.0.0 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of erlpack@discordapp/erlpack but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of libsodium-wrappers@^0.7.3 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of @discordjs/opus@^0.1.0 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of node-opus@^0.2.7 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of opusscript@^0.0.6 but none was installed.`
`npm WARN discord.js@11.6.4 requires a peer of sodium@^2.0.3 but none was installed.`
`npm ERR! Linux 4.4.0-142-generic``npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"`
npm ERR! node v4.2.6`
npm ERR! npm  v3.5.2`
npm ERR! code ELIFECYCLE`

npm ERR! bufferutil@3.0.5 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@3.0.5 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tamberoo/discordIRCd/npm-debug.log
tamberoo@studio1:~/discordIRCd$ `

So, to me it looks like this project requires some certain things:
1. a file or directory in `/usr/bin/env` called `node`
2. some sort of different Linux kernel (probably older)??? since 4.4.0-142-generic seems to make it throw a hissyfit
3. discord.js, erlpack, bufferutil, libsodium-wrappers, node-opus, opusscript, sodium
4. Possibly a lot more that I can't find or know about
My guess it that this project requires all these things. The thing I don't know how to do is install/set up all these dependencies (if that's the right word for them).

Running `uname -a` gives me this output: `Linux studio1 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:01:15 UTC 2019 i686 i686 i686 GNU/Linux` so that way y'all know some info about my machine. And hey, just for the hell of it:
`tamberoo@studio1:~$ screenfetch
                          ./+o+-       tamberoo@studio1
                  yyyyy- -yyyyyy+      OS: Ubuntu 16.04 xenial
               ://+//////-yyyyyyo      Kernel: i686 Linux 4.4.0-142-generic
           .++ .:/++++++/-.+sss/`      Uptime: 12h 14m
         .:++o:  /++++++++/:--:/-      Packages: 1376
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 4.3.48
       .:+o:+o/.          `+sssoo+/    Resolution: 1280x1024
  .++/+:+oo+o:`             /sssooo.   DE: XFCE
 /+++//+:`oo+o               /::--:.   WM: Xfwm4
 \+/+o+++`o++o               ++////.   WM Theme: Windows XP Luna
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Windows XP Luna [GTK2]
       .+.o+oo:.          `oddhhhh+    Icon Theme: Windows-XP-master
        \+.++o+o``-````.:ohdhhhhh+     Font: Sans 9
         `:o+++ `ohhhhhhhhyo++os:      CPU: Genuine Intel CPU T2300 @ 1.667GHz
           .o:`.syhhhhhhh/.oo++o`      RAM: 534MiB / 968MiB
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.      
tamberoo@studio1:~$ `


How would one go about solving this?

**Comment by Chew** [comment]
Yes, you seem to not have `node`, try `node -v` otherwise do `sudo apt-get install node` i believe
